import {BuildContext} from "../builders";

export const generateReadmeText = (ctx: BuildContext, markdownContent: string) => (
`# ${ctx.thisBuildContext.packageName}

| ⚠️⚠️ This folder and all of its contents (recursively) are autogenerated! Modifications will be overwritten! ⚠️⚠️ |
| --- |

1. This package was generated by executing \`proto2pkg\` on \`${ctx.proto2pkgJson.name}\`.
1. [\`${ctx.proto2pkgJson.name}\` can be found here.](${ctx.proto2pkgJson.link})
1. At the time this package was generated:
    1. The \`${ctx.proto2pkgJson.name}\` version was: \`${ctx.proto2pkgJson.version}\`
    1. The \`${ctx.proto2pkgJson.name}\` commit hash was: \`${ctx.commitHash}\`
    1. The build occurred at: ${ctx.buildTime.toISOString()}
1. Below, you can find instructions regarding the generator for this package.

## ${ctx.thisBuildContext.builderName}

${markdownContent}
`
);
// @ts-ignore
